common: &common
  pool: 30
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  recconnect: false

development:
  <<: *common
  database: quiniela_development
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  port: 5432

test:
  <<: *common
  database: quiniela_tests
  username: <%= Rails.application.credentials.db[:username] %>
  password: <%= Rails.application.credentials.db[:password] %>
  port: 5432

# production:
#   <<: *common
#   database: quiniela_production
#   username: postgres
#   password: 12345
#   port: 5432
